// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

// Defines values for BatchStatus.
const (
	Completed  BatchStatus = "completed"
	Processing BatchStatus = "processing"
)

// Valid indicates whether the value is a known member of the BatchStatus enum.
func (e BatchStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// Defines values for Currency.
const (
	EUR Currency = "EUR"
	USD Currency = "USD"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case EUR:
		return true
	case USD:
		return true
	default:
		return false
	}
}

// Defines values for DisbursementStatus.
const (
	Failed  DisbursementStatus = "failed"
	Pending DisbursementStatus = "pending"
	Success DisbursementStatus = "success"
)

// Valid indicates whether the value is a known member of the DisbursementStatus enum.
func (e DisbursementStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeBatchNotFound       ErrorCode = "batch_not_found"
	ErrorCodeDemoResetInProgress ErrorCode = "demo_reset_in_progress"
	ErrorCodeIdempotencyConflict ErrorCode = "idempotency_conflict"
	ErrorCodeInternalError       ErrorCode = "internal_error"
	ErrorCodeInvalidRequest      ErrorCode = "invalid_request"
	ErrorCodeWorkersUnavailable  ErrorCode = "workers_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeBatchNotFound:
		return true
	case ErrorCodeDemoResetInProgress:
		return true
	case ErrorCodeIdempotencyConflict:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeWorkersUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for ProviderErrorCode.
const (
	ProviderDeclined ProviderErrorCode = "provider_declined"
	ProviderError    ProviderErrorCode = "provider_error"
	ProviderTimeout  ProviderErrorCode = "provider_timeout"
)

// Valid indicates whether the value is a known member of the ProviderErrorCode enum.
func (e ProviderErrorCode) Valid() bool {
	switch e {
	case ProviderDeclined:
		return true
	case ProviderError:
		return true
	case ProviderTimeout:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	AlreadyPaid    UnavailableReason = "already_paid"
	AlreadyPending UnavailableReason = "already_pending"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case AlreadyPaid:
		return true
	case AlreadyPending:
		return true
	default:
		return false
	}
}

// BatchID Example: batch-8cdfbc42-fde7-4a5f-a169-8f76b14be475
type BatchID = string

// BatchSnapshot defines model for BatchSnapshot.
type BatchSnapshot struct {
	// BatchID Example: batch-8cdfbc42-fde7-4a5f-a169-8f76b14be475
	BatchID BatchID              `json:"batch_id"`
	Results []DisbursementResult `json:"results"`
	Status  BatchStatus          `json:"status"`
}

// BatchStatus defines model for BatchStatus.
type BatchStatus string

// Currency defines model for Currency.
type Currency string

// DisbursementResult defines model for DisbursementResult.
type DisbursementResult struct {
	Amount   string   `json:"amount"`
	Currency Currency `json:"currency"`

	// DisbursementID Example: disb-fc09316e
	DisbursementID string `json:"disbursement_id"`

	// Error Present only when status is failed.
	Error *ProviderErrorCode `json:"error,omitempty"`

	// ErrorMessage Present only when status is failed.
	ErrorMessage *string `json:"error_message,omitempty"`

	// ProviderTxnID Present only when status is success.
	//
	// Example: ptx-e41723a4
	ProviderTxnID *string            `json:"provider_txn_id,omitempty"`
	Status        DisbursementStatus `json:"status"`

	// WorkerID Example: w-001
	WorkerID   WorkerID `json:"worker_id"`
	WorkerName string   `json:"worker_name"`
}

// DisbursementStatus defines model for DisbursementStatus.
type DisbursementStatus string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code               ErrorCode            `json:"code"`
	Message            string               `json:"message"`
	RequestID          string               `json:"request_id"`
	UnavailableWorkers *[]UnavailableWorker `json:"unavailable_workers,omitempty"`
}

// ProviderErrorCode defines model for ProviderErrorCode.
type ProviderErrorCode string

// SubmitBatchRequest defines model for SubmitBatchRequest.
type SubmitBatchRequest struct {
	// BatchID Example: batch-8cdfbc42-fde7-4a5f-a169-8f76b14be475
	BatchID   BatchID    `json:"batch_id"`
	WorkerIDs []WorkerID `json:"worker_ids"`
}

// SubmitBatchResponse defines model for SubmitBatchResponse.
type SubmitBatchResponse struct {
	// BatchID Example: batch-8cdfbc42-fde7-4a5f-a169-8f76b14be475
	BatchID BatchID `json:"batch_id"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// UnavailableWorker defines model for UnavailableWorker.
type UnavailableWorker struct {
	// BatchID Example: batch-8cdfbc42-fde7-4a5f-a169-8f76b14be475
	BatchID        BatchID           `json:"batch_id"`
	DisbursementID string            `json:"disbursement_id"`
	Reason         UnavailableReason `json:"reason"`

	// WorkerID Example: w-001
	WorkerID   WorkerID `json:"worker_id"`
	WorkerName string   `json:"worker_name"`
}

// Worker defines model for Worker.
type Worker struct {
	// Amount Example: 1500.50
	Amount   string   `json:"amount"`
	Currency Currency `json:"currency"`

	// ID Example: w-001
	ID WorkerID `json:"id"`

	// Name Example: Maya Thompson
	Name string `json:"name"`
}

// WorkerID Example: w-001
type WorkerID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// SubmitDisbursementsJSONRequestBody defines body for SubmitDisbursements for application/json ContentType.
type SubmitDisbursementsJSONRequestBody = SubmitBatchRequest
